import { renderToStaticMarkup } from "react-dom/server"
import { createElement } from "react"
import JSZip from "jszip"
import { SectionInstance } from "@/types/section"
import { templateMap } from "@/lib/sections/library"

const LYNQ_COMMENT_JS = `// Generated by Lynq — https://lynq.app`
const LYNQ_COMMENT_HTML = `<!-- Generated by Lynq — https://lynq.app -->`
const LYNQ_FOOTER_HTML = `
<footer style="padding: 32px; text-align: center; border-top: 1px solid rgba(255,255,255,0.06);">
  <span style="font-family: system-ui, sans-serif; font-size: 12px; color: rgba(255,255,255,0.25); letter-spacing: 0.05em;">
    Built with <a href="https://lynq.app" style="color: rgba(255,255,255,0.4); text-decoration: none;">Lynq</a>
  </span>
</footer>`

// ─── Shared utils ─────────────────────────────────────────────────────────────

function getComponentName(component: React.ComponentType<any>): string {
  return component.displayName ?? component.name ?? "UnknownSection"
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}

function toPascalCase(str: string): string {
  return (
    str
      .replace(/[^a-zA-Z0-9\s]/g, "")
      .split(/\s+/)
      .filter(Boolean)
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
      .join("")
  ) || "MyPage"
}

export function slugify(str: string): string {
  return (
    str
      .toLowerCase()
      .replace(/\s+/g, "-")
      .replace(/[^a-z0-9-]/g, "")
  ) || "project"
}

export function generateReact(sections: SectionInstance[], projectName: string): string {
  const importLines: string[] = []
  const seen = new Set<string>()
  for (const instance of sections) {
    if (seen.has(instance.templateId)) continue
    seen.add(instance.templateId)
    const template = templateMap.get(instance.templateId)
    if (!template) continue
    const name = getComponentName(template.component)
    importLines.push(`import ${name} from "@/components/sections/${instance.type}/${instance.theme}/${name}"`)
  }

  const jsxBlocks = sections.map((instance) => {
    const template = templateMap.get(instance.templateId)
    if (!template) return `  {/* template not found */}`
    const name = getComponentName(template.component)
    const props = Object.entries(instance.content)
      .map(([k, v]) => typeof v === "string" ? `    ${k}=${JSON.stringify(v)}` : `    ${k}={${JSON.stringify(v)}}`)
      .join("\n")
    return `  <${name}\n${props}\n  />`
  }).join("\n\n")

  const componentName = toPascalCase(projectName)
  return `${LYNQ_COMMENT_JS}\n\n${importLines.join("\n")}\n\nexport default function ${componentName}() {\n  return (\n    <main>\n\n${jsxBlocks}\n\n    </main>\n  )\n}\n`
}

export function downloadFile(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

// ─── Render one section to static HTML string ─────────────────────────────────

function renderInstanceToHTML(instance: SectionInstance): string {
  const template = templateMap.get(instance.templateId)
  if (!template) return `<!-- template "${instance.templateId}" not found -->`

  try {
    return renderToStaticMarkup(
      createElement(template.component, instance.content)
    )
  } catch (err) {
    console.warn(`[export] Failed to render "${instance.templateId}":`, err)
    return `<!-- render failed for "${instance.templateId}" -->`
  }
}

// ─── Get the raw source of a component file ───────────────────────────────────

function buildSelfContainedComponent(instance: SectionInstance): string {
  const template = templateMap.get(instance.templateId)
  if (!template) return ""

  const name = getComponentName(template.component)

  // Build typed props interface from defaultContent keys
  const propEntries = Object.entries(instance.content)
  const propsInterface = propEntries.length > 0
    ? `interface Props {\n${propEntries.map(([k, v]) => `  ${k}?: ${inferTSType(v)}`).join("\n")}\n}`
    : ""

  const propsList = propEntries.map(([k]) => k).join(", ")
  const defaultProps = propEntries
    .map(([k, v]) => `  ${k} = ${JSON.stringify(v)}`)
    .join(",\n")

  // Render the actual HTML output of this component with the given content
  const rendered = renderInstanceToHTML(instance)

  return `${LYNQ_COMMENT_JS}

${propsInterface}

export default function ${name}({
${defaultProps}
}: ${propsInterface ? "Props" : "Record<string, never>"}) {
  return (
    ${rendered
      // Convert HTML attributes to JSX (basic)
      .replace(/class=/g, "className=")
      .replace(/for=/g, "htmlFor=")
      // Self-close void elements
      .replace(/<(br|hr|img|input|meta|link)([^>]*)>/g, "<$1$2 />")
    }
  )
}
`
}

function inferTSType(value: unknown): string {
  if (typeof value === "string") return "string"
  if (typeof value === "number") return "number"
  if (typeof value === "boolean") return "boolean"
  if (Array.isArray(value)) return "any[]"
  if (value !== null && typeof value === "object") return "Record<string, any>"
  return "any"
}

// ─── HTML export (single file) ────────────────────────────────────────────────

export function generateHTML(
  sections: SectionInstance[],
  projectName: string
): string {
  const body = sections.map(renderInstanceToHTML).join("\n\n")

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(projectName)}</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <style>
    *, *::before, *::after { box-sizing: border-box; }
    body { margin: 0; font-family: system-ui, -apple-system, sans-serif; background: #000; color: #fff; }
  </style>
</head>
<body>

${body}
${LYNQ_FOOTER_HTML}

</body>
</html>
${LYNQ_COMMENT_HTML}`
}

// ─── React export (ZIP) ───────────────────────────────────────────────────────

export async function generateReactZip(
  sections: SectionInstance[],
  projectName: string
): Promise<Blob> {
  const zip = new JSZip()
  const slug = slugify(projectName)
  const pageComponentName = toPascalCase(projectName)

  // Track which templateIds we've already written (dedup)
  const written = new Map<string, string>() // templateId → import path

  // ── 1. Write each unique section component ──────────────────────────────
  for (const instance of sections) {
    if (written.has(instance.templateId)) continue

    const template = templateMap.get(instance.templateId)
    if (!template) continue

    const name = getComponentName(template.component)
    const filePath = `components/sections/${instance.type}/${instance.theme}/${name}.tsx`
    const importPath = `./components/sections/${instance.type}/${instance.theme}/${name}`

    zip.file(filePath, buildSelfContainedComponent(instance))
    written.set(instance.templateId, importPath)
  }

  // ── 2. Build the page component ─────────────────────────────────────────
  const importLines = sections
    .filter((inst, idx, arr) => arr.findIndex(i => i.templateId === inst.templateId) === idx)
    .map((inst) => {
      const template = templateMap.get(inst.templateId)
      if (!template) return null
      const name = getComponentName(template.component)
      const path = written.get(inst.templateId)!
      return `import ${name} from "${path}"`
    })
    .filter(Boolean)
    .join("\n")

  const jsxSections = sections.map((instance) => {
    const template = templateMap.get(instance.templateId)
    if (!template) return `  {/* template not found: ${instance.templateId} */}`

    const name = getComponentName(template.component)
    const props = Object.entries(instance.content)
      .map(([k, v]) =>
        typeof v === "string"
          ? `    ${k}=${JSON.stringify(v)}`
          : `    ${k}={${JSON.stringify(v)}}`
      )
      .join("\n")

    return `  {/* ${template.name} */}\n  <${name}\n${props}\n  />`
  }).join("\n\n")

  const lynqFooterJSX = `
  {/* Generated by Lynq */}
  <footer style={{ padding: "32px", textAlign: "center", borderTop: "1px solid rgba(255,255,255,0.06)" }}>
    <span style={{ fontFamily: "system-ui, sans-serif", fontSize: "12px", color: "rgba(255,255,255,0.25)", letterSpacing: "0.05em" }}>
      Built with{" "}
      <a href="https://lynq.app" style={{ color: "rgba(255,255,255,0.4)", textDecoration: "none" }}>
        Lynq
      </a>
    </span>
  </footer>`

  const pageFile = `${LYNQ_COMMENT_JS}

${importLines}

export default function ${pageComponentName}() {
  return (
    <main>

${jsxSections}
${lynqFooterJSX}

    </main>
  )
}
`

  zip.file(`${slug}.tsx`, pageFile)

  // ── 3. README ────────────────────────────────────────────────────────────
  zip.file("README.md", buildReadme(projectName, slug, pageComponentName, sections))

  return zip.generateAsync({ type: "blob", compression: "DEFLATE" })
}

// ─── README ───────────────────────────────────────────────────────────────────

function buildReadme(
  projectName: string,
  slug: string,
  componentName: string,
  sections: SectionInstance[]
): string {
  const sectionList = sections
    .map((inst) => {
      const t = templateMap.get(inst.templateId)
      return `- **${t?.name ?? inst.templateId}** (\`${inst.type}\` · \`${inst.theme}\`)`
    })
    .join("\n")

  return `# ${projectName}

> Generated by [Lynq](https://lynq.app)

## Usage

Copy \`${slug}.tsx\` and the \`components/\` folder into your Next.js project, then:

\`\`\`tsx
import ${componentName} from "./${slug}"

export default function Page() {
  return <${componentName} />
}
\`\`\`

Make sure Tailwind CSS is configured in your project.

## Sections (${sections.length})

${sectionList}

---

*Built with Lynq*
`
}